version: '2'
services:
  phabricator:
    restart: always
    ports:
     - "62443:443"
     - "62080:80"
     - "62022:22"
    volumes:
     - /Users/tangcheng/WebSite/docker/phabricator/repos:/repos
     - /Users/tangcheng/WebSite/docker/phabricator/extensions:/srv/phabricator/phabricator/src/extensions
    depends_on:
     - mysql
    links:
     - mysql
    environment:
     - MYSQL_HOST=mysql
     - MYSQL_USER=root
     - MYSQL_PASS=phabricator
     - PHABRICATOR_REPOSITORY_PATH=/repos
     - PHABRICATOR_HOST=myphabricator.tc.com
    image: vergils/phabricator
  mysql:
    restart: always
    volumes:
     - /Users/tangcheng/WebSite/docker/phabricator/mysql:/var/lib/mysql
    image: mysql:5.7.14
    environment:
     - MYSQL_ROOT_PASSWORD=phabricator
